In [76]:
import numpy as np

In [77]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [50]:
liste = ["Melih", 20, True, 10.4]

In [48]:
liste_1 = ["Melis", 25, True, 87.5]
liste_1

['Melis', 25, True, 87.5]

In [51]:
liste

['Melih', 20, True, 10.4]

In [ ]:
print(type(liste[0]))
print(type(liste[1]))
print(type(liste[2]))
print(type(liste[3]))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


In [60]:
arr = np.array([20, False, 10.4])

In [57]:
arr

array([20. ,  0. , 10.4])

In [59]:
print(type(arr[0]))
print(type(arr[1]))
print(type(arr[2]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [25]:
arr = np.array([20, False])
arr

array([20,  0])

In [26]:
print(type(arr[0]))
print(type(arr[1]))

<class 'numpy.int64'>
<class 'numpy.int64'>


In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr

array([1, 2, 3, 4, 5])

In [31]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.full((5,5), 152)

array([[152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152]])

In [41]:
np.random.randint(0,10, (10,10))

array([[7, 7, 5, 4, 8, 5, 6, 8, 4, 4],
       [2, 3, 9, 3, 0, 4, 6, 6, 9, 8],
       [6, 1, 1, 7, 0, 4, 7, 2, 4, 3],
       [1, 2, 9, 4, 5, 4, 3, 2, 9, 1],
       [7, 8, 8, 9, 8, 5, 2, 3, 0, 9],
       [3, 7, 5, 8, 8, 2, 2, 2, 9, 3],
       [1, 2, 8, 7, 9, 1, 2, 6, 5, 3],
       [3, 3, 7, 1, 1, 5, 6, 9, 4, 2],
       [6, 1, 7, 6, 8, 7, 3, 1, 4, 9],
       [4, 5, 1, 0, 9, 1, 3, 5, 5, 4]])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.linspace(5,9.4,50)

array([5.        , 5.08979592, 5.17959184, 5.26938776, 5.35918367,
       5.44897959, 5.53877551, 5.62857143, 5.71836735, 5.80816327,
       5.89795918, 5.9877551 , 6.07755102, 6.16734694, 6.25714286,
       6.34693878, 6.43673469, 6.52653061, 6.61632653, 6.70612245,
       6.79591837, 6.88571429, 6.9755102 , 7.06530612, 7.15510204,
       7.24489796, 7.33469388, 7.4244898 , 7.51428571, 7.60408163,
       7.69387755, 7.78367347, 7.87346939, 7.96326531, 8.05306122,
       8.14285714, 8.23265306, 8.32244898, 8.4122449 , 8.50204082,
       8.59183673, 8.68163265, 8.77142857, 8.86122449, 8.95102041,
       9.04081633, 9.13061224, 9.22040816, 9.31020408, 9.4       ])

In [75]:
arr = np.array([1,2,3,4,5], dtype=np.float16)
arr

array([1., 2., 3., 4., 5.], dtype=float16)

In [73]:
arr = np.array([1.6,3.5,2.9,5.2,4.3,2.1], dtype = np.float16)
arr

array([1.6, 3.5, 2.9, 5.2, 4.3, 2.1], dtype=float16)

In [74]:
arr = np.array([1.6,3.5,2.9,5.2,4.3,2.1], dtype = np.int8)
arr

array([1, 3, 2, 5, 4, 2], dtype=int8)

In [79]:
arr = np.array([1,2,3,4,5], dtype=np.complex128)
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [91]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [92]:
array_1.ndim

1

In [93]:
array_1.shape

(5,)

In [95]:
array_2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
array_2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [96]:
array_2.ndim

2

In [94]:
array_2.shape

(2, 5)

In [97]:
array_2.size

10

In [98]:
len(array_2)

2

In [99]:
len(array_1)

5

In [104]:
arr0 = np.array(5)
arr1 = np.array([1,2])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])

In [105]:
arr0

array(5)

In [106]:
arr1

array([1, 2])

In [107]:
arr2

array([[1, 2],
       [3, 4]])

In [108]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [109]:
arr3.ndim

3

In [110]:
arr2.ndim

2

In [111]:
arr3.size

8

In [112]:
len(arr3)

2

In [114]:
print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

()
(2,)
(2, 2)
(2, 2, 2)


In [115]:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [118]:
array = np.array([1,2,3,4,5])
array[3]

4

In [119]:
array = np.random.randint(0,10, (6,6))
array

array([[2, 7, 2, 8, 9, 9],
       [0, 4, 5, 8, 1, 0],
       [9, 0, 8, 2, 7, 4],
       [8, 2, 3, 6, 7, 1],
       [5, 1, 0, 2, 9, 1],
       [9, 3, 2, 3, 8, 8]])

In [120]:
array[3]

array([8, 2, 3, 6, 7, 1])

In [121]:
array[:4]

array([[2, 7, 2, 8, 9, 9],
       [0, 4, 5, 8, 1, 0],
       [9, 0, 8, 2, 7, 4],
       [8, 2, 3, 6, 7, 1]])

In [122]:
array[1,4]

1

In [123]:
array[2,:]

array([9, 0, 8, 2, 7, 4])

In [124]:
array[1,2:4]

array([5, 8])

In [125]:
array[2,2:4]

array([8, 2])

In [126]:
array[3,1:4]

array([2, 3, 6])

In [127]:
array[2:4,2:4]

array([[8, 2],
       [3, 6]])

In [128]:
array = np.array([436,342,765,142,33,54,80,46])

In [130]:
sorted_data = np.sort(array)
sorted_data

array([ 33,  46,  54,  80, 142, 342, 436, 765])

In [131]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [132]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [138]:
z = np.array([7,8,9])

In [139]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
new_array1 = np.array([[1,2,3], [4,5,6]])

In [151]:
new_array = np.concatenate([new_array1, new_array1], axis=0)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [152]:
new_array = np.concatenate([new_array1, new_array1], axis=1)
new_array

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [159]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [160]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])