<a href="https://colab.research.google.com/github/dilaraesmer/Global_AI_Hub-Data_Manipulation/blob/main/Global_AI_Hub_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
liste = ["Melih", 20, True, 10.4]

In [7]:
liste_1 = ["Melis", 25, True, 87.5]
liste_1

['Melis', 25, True, 87.5]

In [8]:
liste

['Melih', 20, True, 10.4]

In [9]:
print(type(liste[0]))
print(type(liste[1]))
print(type(liste[2]))
print(type(liste[3]))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


In [10]:
arr = np.array([20, False, 10.4])

In [11]:
arr

array([20. ,  0. , 10.4])

In [12]:
print(type(arr[0]))
print(type(arr[1]))
print(type(arr[2]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [13]:
arr = np.array([20, False])
arr

array([20,  0])

In [14]:
print(type(arr[0]))
print(type(arr[1]))

<class 'numpy.int64'>
<class 'numpy.int64'>


In [15]:
arr = np.array([1,2,3,4,5])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((5,5), 152)

array([[152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152],
       [152, 152, 152, 152, 152]])

In [21]:
np.random.randint(0,10, (10,10))

array([[2, 9, 4, 6, 5, 5, 1, 4, 8, 0],
       [6, 2, 1, 6, 6, 9, 4, 2, 8, 0],
       [6, 9, 2, 7, 9, 9, 0, 2, 8, 5],
       [3, 9, 5, 4, 6, 3, 0, 7, 7, 6],
       [5, 3, 7, 5, 9, 8, 6, 1, 4, 1],
       [4, 8, 2, 5, 3, 3, 4, 6, 0, 7],
       [8, 3, 9, 9, 9, 3, 7, 2, 8, 9],
       [6, 3, 2, 3, 8, 8, 7, 0, 7, 4],
       [5, 0, 3, 8, 5, 7, 8, 9, 8, 1],
       [7, 4, 9, 2, 1, 8, 0, 5, 0, 8]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.linspace(5,9.4,50)

array([5.        , 5.08979592, 5.17959184, 5.26938776, 5.35918367,
       5.44897959, 5.53877551, 5.62857143, 5.71836735, 5.80816327,
       5.89795918, 5.9877551 , 6.07755102, 6.16734694, 6.25714286,
       6.34693878, 6.43673469, 6.52653061, 6.61632653, 6.70612245,
       6.79591837, 6.88571429, 6.9755102 , 7.06530612, 7.15510204,
       7.24489796, 7.33469388, 7.4244898 , 7.51428571, 7.60408163,
       7.69387755, 7.78367347, 7.87346939, 7.96326531, 8.05306122,
       8.14285714, 8.23265306, 8.32244898, 8.4122449 , 8.50204082,
       8.59183673, 8.68163265, 8.77142857, 8.86122449, 8.95102041,
       9.04081633, 9.13061224, 9.22040816, 9.31020408, 9.4       ])

In [24]:
arr = np.array([1,2,3,4,5], dtype=np.float16)
arr

array([1., 2., 3., 4., 5.], dtype=float16)

In [25]:
arr = np.array([1.6,3.5,2.9,5.2,4.3,2.1], dtype = np.float16)
arr

array([1.6, 3.5, 2.9, 5.2, 4.3, 2.1], dtype=float16)

In [26]:
arr = np.array([1.6,3.5,2.9,5.2,4.3,2.1], dtype = np.int8)
arr

array([1, 3, 2, 5, 4, 2], dtype=int8)

In [27]:
arr = np.array([1,2,3,4,5], dtype=np.complex128)
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [28]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [29]:
array_1.ndim

1

In [30]:
array_1.shape

(5,)

In [31]:
array_2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
array_2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [32]:
array_2.ndim

2

In [33]:
array_2.shape

(2, 5)

In [34]:
array_2.size

10

In [35]:
len(array_2)

2

In [36]:
len(array_1)

5

In [37]:
arr0 = np.array(5)
arr1 = np.array([1,2])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])

In [38]:
arr0

array(5)

In [39]:
arr1

array([1, 2])

In [40]:
arr2

array([[1, 2],
       [3, 4]])

In [41]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
arr3.ndim

3

In [43]:
arr2.ndim

2

In [44]:
arr3.size

8

In [45]:
len(arr3)

2

In [46]:
print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

()
(2,)
(2, 2)
(2, 2, 2)


In [47]:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [48]:
array = np.array([1,2,3,4,5])
array[3]

4

In [49]:
array = np.random.randint(0,10, (6,6))
array

array([[7, 6, 1, 3, 6, 4],
       [4, 3, 5, 6, 1, 8],
       [3, 8, 1, 9, 1, 0],
       [9, 3, 3, 5, 2, 7],
       [5, 1, 0, 4, 9, 5],
       [7, 3, 9, 6, 1, 7]])

In [50]:
array[3]

array([9, 3, 3, 5, 2, 7])

In [51]:
array[:4]

array([[7, 6, 1, 3, 6, 4],
       [4, 3, 5, 6, 1, 8],
       [3, 8, 1, 9, 1, 0],
       [9, 3, 3, 5, 2, 7]])

In [52]:
array[1,4]

1

In [53]:
array[2,:]

array([3, 8, 1, 9, 1, 0])

In [54]:
array[1,2:4]

array([5, 6])

In [55]:
array[2,2:4]

array([1, 9])

In [56]:
array[3,1:4]

array([3, 3, 5])

In [57]:
array[2:4,2:4]

array([[1, 9],
       [3, 5]])

In [58]:
array = np.array([436,342,765,142,33,54,80,46])

In [59]:
sorted_data = np.sort(array)
sorted_data

array([ 33,  46,  54,  80, 142, 342, 436, 765])

In [60]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [61]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [62]:
z = np.array([7,8,9])

In [63]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
new_array1 = np.array([[1,2,3], [4,5,6]])

In [65]:
new_array = np.concatenate([new_array1, new_array1], axis=0)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
new_array = np.concatenate([new_array1, new_array1], axis=1)
new_array

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [69]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
arr = np.random.randint(0,10,(4,15))
arr

array([[1, 5, 8, 8, 1, 9, 5, 5, 5, 9, 2, 2, 9, 7, 2],
       [2, 8, 7, 5, 0, 9, 6, 4, 5, 3, 9, 4, 5, 0, 6],
       [4, 3, 1, 1, 6, 5, 8, 5, 9, 9, 5, 5, 2, 7, 0],
       [5, 6, 7, 0, 3, 7, 1, 7, 8, 8, 1, 6, 6, 2, 6]])

In [71]:
arr.reshape(10,6)

array([[1, 5, 8, 8, 1, 9],
       [5, 5, 5, 9, 2, 2],
       [9, 7, 2, 2, 8, 7],
       [5, 0, 9, 6, 4, 5],
       [3, 9, 4, 5, 0, 6],
       [4, 3, 1, 1, 6, 5],
       [8, 5, 9, 9, 5, 5],
       [2, 7, 0, 5, 6, 7],
       [0, 3, 7, 1, 7, 8],
       [8, 1, 6, 6, 2, 6]])

In [72]:
arr[-2]

array([4, 3, 1, 1, 6, 5, 8, 5, 9, 9, 5, 5, 2, 7, 0])

In [73]:
arr+1

array([[ 2,  6,  9,  9,  2, 10,  6,  6,  6, 10,  3,  3, 10,  8,  3],
       [ 3,  9,  8,  6,  1, 10,  7,  5,  6,  4, 10,  5,  6,  1,  7],
       [ 5,  4,  2,  2,  7,  6,  9,  6, 10, 10,  6,  6,  3,  8,  1],
       [ 6,  7,  8,  1,  4,  8,  2,  8,  9,  9,  2,  7,  7,  3,  7]])

In [74]:
arr*2

array([[ 2, 10, 16, 16,  2, 18, 10, 10, 10, 18,  4,  4, 18, 14,  4],
       [ 4, 16, 14, 10,  0, 18, 12,  8, 10,  6, 18,  8, 10,  0, 12],
       [ 8,  6,  2,  2, 12, 10, 16, 10, 18, 18, 10, 10,  4, 14,  0],
       [10, 12, 14,  0,  6, 14,  2, 14, 16, 16,  2, 12, 12,  4, 12]])

In [75]:
np.add(arr,3)

array([[ 4,  8, 11, 11,  4, 12,  8,  8,  8, 12,  5,  5, 12, 10,  5],
       [ 5, 11, 10,  8,  3, 12,  9,  7,  8,  6, 12,  7,  8,  3,  9],
       [ 7,  6,  4,  4,  9,  8, 11,  8, 12, 12,  8,  8,  5, 10,  3],
       [ 8,  9, 10,  3,  6, 10,  4, 10, 11, 11,  4,  9,  9,  5,  9]])

In [76]:
np.multiply(arr,3)

array([[ 3, 15, 24, 24,  3, 27, 15, 15, 15, 27,  6,  6, 27, 21,  6],
       [ 6, 24, 21, 15,  0, 27, 18, 12, 15,  9, 27, 12, 15,  0, 18],
       [12,  9,  3,  3, 18, 15, 24, 15, 27, 27, 15, 15,  6, 21,  0],
       [15, 18, 21,  0,  9, 21,  3, 21, 24, 24,  3, 18, 18,  6, 18]])

In [77]:
array = np.array([1,2,3,4,5,6,7,8])

In [78]:
array > 4

array([False, False, False, False,  True,  True,  True,  True])

In [79]:
array < 3

array([ True,  True, False, False, False, False, False, False])

In [80]:
array[array<6]

array([1, 2, 3, 4, 5])

In [81]:
array[~(array>3)]

array([1, 2, 3])

In [82]:
array[array != 3]

array([1, 2, 4, 5, 6, 7, 8])